### ISSUE TITLE
What is the reason for calculating the loss and pass it to the backward function as gradient parameter?

### ISSUE THREAD

**Issue by Eliyas0007** [tanelp/tiny-diffusion#3]

**Comment by toannguyen1904** [comment]
same question

**Comment by bkkm78** [comment]
I am also confused about this. The end result is that gradients are scaled according to the magnitude of the loss. Maybe this is some learning rate scheduling wizardry?

**Comment by tanelp** [comment]
Hmm, looks like this was committed by mistake. Changed in [this](https://github.com/tanelp/tiny-diffusion/commit/726b6bbbf2c9e3d23dff9eaea2fda10d0af6a78c) commit. Thanks!
